//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeifenLuo.WinFormsUI.ThemeVS2012Light {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeifenLuo.WinFormsUI.ThemeVS2012Light.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Docking ähnelt.
        /// </summary>
        internal static string Category_Docking {
            get {
                return ResourceManager.GetString("Category_Docking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Docking Notification ähnelt.
        /// </summary>
        internal static string Category_DockingNotification {
            get {
                return ResourceManager.GetString("Category_DockingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Performance ähnelt.
        /// </summary>
        internal static string Category_Performance {
            get {
                return ResourceManager.GetString("Category_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Property Changed ähnelt.
        /// </summary>
        internal static string Category_PropertyChanged {
            get {
                return ResourceManager.GetString("Category_PropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Float) ähnelt.
        /// </summary>
        internal static string DockAreaEditor_FloatCheckBoxText {
            get {
                return ResourceManager.GetString("DockAreaEditor_FloatCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Determines if end user drag and drop docking is allowed. ähnelt.
        /// </summary>
        internal static string DockContent_AllowEndUserDocking_Description {
            get {
                return ResourceManager.GetString("DockContent_AllowEndUserDocking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The size to display the content in auto hide mode. Value &lt; 1 to specify the size in portion; value &gt;= 1 to specify the size in pixel. ähnelt.
        /// </summary>
        internal static string DockContent_AutoHidePortion_Description {
            get {
                return ResourceManager.GetString("DockContent_AutoHidePortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable/Disable the close button of the content. ähnelt.
        /// </summary>
        internal static string DockContent_CloseButton_Description {
            get {
                return ResourceManager.GetString("DockContent_CloseButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shows or hides the close button of the content. This property does not function with System MDI Document Style. ähnelt.
        /// </summary>
        internal static string DockContent_CloseButtonVisible_Description {
            get {
                return ResourceManager.GetString("DockContent_CloseButtonVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The form must be of type IDockContent. ähnelt.
        /// </summary>
        internal static string DockContent_Constructor_InvalidForm {
            get {
                return ResourceManager.GetString("DockContent_Constructor_InvalidForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gets or sets a value indicating in which area of the DockPanel the content allowed to show. ähnelt.
        /// </summary>
        internal static string DockContent_DockAreas_Description {
            get {
                return ResourceManager.GetString("DockContent_DockAreas_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occurs when the value of DockState property changed. ähnelt.
        /// </summary>
        internal static string DockContent_DockStateChanged_Description {
            get {
                return ResourceManager.GetString("DockContent_DockStateChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Indicates the content will be hidden instead of being closed. ähnelt.
        /// </summary>
        internal static string DockContent_HideOnClose_Description {
            get {
                return ResourceManager.GetString("DockContent_HideOnClose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The desired docking state when first showing. ähnelt.
        /// </summary>
        internal static string DockContent_ShowHint_Description {
            get {
                return ResourceManager.GetString("DockContent_ShowHint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Context menu displayed for the dock pane tab strip. ähnelt.
        /// </summary>
        internal static string DockContent_TabPageContextMenu_Description {
            get {
                return ResourceManager.GetString("DockContent_TabPageContextMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The tab text displayed in the dock pane. If not set, the Text property will be used. ähnelt.
        /// </summary>
        internal static string DockContent_TabText_Description {
            get {
                return ResourceManager.GetString("DockContent_TabText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The text displayed when mouse hovers over the tab. ähnelt.
        /// </summary>
        internal static string DockContent_ToolTipText_Description {
            get {
                return ResourceManager.GetString("DockContent_ToolTipText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The provided value is out of range. ähnelt.
        /// </summary>
        internal static string DockContentHandler_AutoHidePortion_OutOfRange {
            get {
                return ResourceManager.GetString("DockContentHandler_AutoHidePortion_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Value: The value of DockAreas conflicts with current DockState. ähnelt.
        /// </summary>
        internal static string DockContentHandler_DockAreas_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_DockAreas_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The pane is invalid. Check the IsFloat and DockPanel properties of this dock pane. ähnelt.
        /// </summary>
        internal static string DockContentHandler_DockPane_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_DockPane_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The pane is invalid. Check the IsFloat and DockPanel properties of this dock pane. ähnelt.
        /// </summary>
        internal static string DockContentHandler_FloatPane_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_FloatPane_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid value, conflicts with DockableAreas  property. ähnelt.
        /// </summary>
        internal static string DockContentHandler_IsFloat_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_IsFloat_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The dock state is invalid. ähnelt.
        /// </summary>
        internal static string DockContentHandler_SetDockState_InvalidState {
            get {
                return ResourceManager.GetString("DockContentHandler_SetDockState_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The dock panel is null. ähnelt.
        /// </summary>
        internal static string DockContentHandler_SetDockState_NullPanel {
            get {
                return ResourceManager.GetString("DockContentHandler_SetDockState_NullPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid beforeContent, it must be contained by the pane. ähnelt.
        /// </summary>
        internal static string DockContentHandler_Show_InvalidBeforeContent {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_InvalidBeforeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid DockState: Content can not be showed as &quot;Unknown&quot; or &quot;Hidden&quot;. ähnelt.
        /// </summary>
        internal static string DockContentHandler_Show_InvalidDockState {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_InvalidDockState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The previous pane is invalid. It can not be null, and its docking state must not be auto-hide. ähnelt.
        /// </summary>
        internal static string DockContentHandler_Show_InvalidPrevPane {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_InvalidPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DockPanel can not be null. ähnelt.
        /// </summary>
        internal static string DockContentHandler_Show_NullDockPanel {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_NullDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Pane can not be null. ähnelt.
        /// </summary>
        internal static string DockContentHandler_Show_NullPane {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_NullPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid value, check DockableAreas property. ähnelt.
        /// </summary>
        internal static string DockContentHandler_ShowHint_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_ShowHint_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Context menu displayed for the dock pane tab strip. ähnelt.
        /// </summary>
        internal static string DockHandler_TabPageContextMenuStrip_Description {
            get {
                return ResourceManager.GetString("DockHandler_TabPageContextMenuStrip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press SHIFT for docking to full side. ähnelt.
        /// </summary>
        internal static string DockIndicator_ToolTipText {
            get {
                return ResourceManager.GetString("DockIndicator_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Content: ActiveContent must be one of the visible contents, or null if there is no visible content. ähnelt.
        /// </summary>
        internal static string DockPane_ActiveContent_InvalidValue {
            get {
                return ResourceManager.GetString("DockPane_ActiveContent_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid argument: Content can not be &quot;null&quot;. ähnelt.
        /// </summary>
        internal static string DockPane_Constructor_NullContent {
            get {
                return ResourceManager.GetString("DockPane_Constructor_NullContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid argument: The content&apos;s DockPanel can not be &quot;null&quot;. ähnelt.
        /// </summary>
        internal static string DockPane_Constructor_NullDockPanel {
            get {
                return ResourceManager.GetString("DockPane_Constructor_NullDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified container conflicts with the IsFloat property. ähnelt.
        /// </summary>
        internal static string DockPane_DockTo_InvalidContainer {
            get {
                return ResourceManager.GetString("DockPane_DockTo_InvalidContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The previous pane does not exist in the nested docking pane collection. ähnelt.
        /// </summary>
        internal static string DockPane_DockTo_NoPrevPane {
            get {
                return ResourceManager.GetString("DockPane_DockTo_NoPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The container can not be null. ähnelt.
        /// </summary>
        internal static string DockPane_DockTo_NullContainer {
            get {
                return ResourceManager.GetString("DockPane_DockTo_NullContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The previous pane can not be null when the nested docking pane collection is not empty. ähnelt.
        /// </summary>
        internal static string DockPane_DockTo_NullPrevPane {
            get {
                return ResourceManager.GetString("DockPane_DockTo_NullPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The previous pane can not be itself. ähnelt.
        /// </summary>
        internal static string DockPane_DockTo_SelfPrevPane {
            get {
                return ResourceManager.GetString("DockPane_DockTo_SelfPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FloatWindow property can not be set to &quot;null&quot; when DockState is DockState.Float. ähnelt.
        /// </summary>
        internal static string DockPane_FloatWindow_InvalidValue {
            get {
                return ResourceManager.GetString("DockPane_FloatWindow_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Content: Content not within the collection. ähnelt.
        /// </summary>
        internal static string DockPane_SetContentIndex_InvalidContent {
            get {
                return ResourceManager.GetString("DockPane_SetContentIndex_InvalidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Index: The index is out of range. ähnelt.
        /// </summary>
        internal static string DockPane_SetContentIndex_InvalidIndex {
            get {
                return ResourceManager.GetString("DockPane_SetContentIndex_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The state for the dock pane is invalid. ähnelt.
        /// </summary>
        internal static string DockPane_SetDockState_InvalidState {
            get {
                return ResourceManager.GetString("DockPane_SetDockState_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Hide ähnelt.
        /// </summary>
        internal static string DockPaneCaption_ToolTipAutoHide {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipAutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string DockPaneCaption_ToolTipClose {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximize ähnelt.
        /// </summary>
        internal static string DockPaneCaption_ToolTipMaximize {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string DockPaneCaption_ToolTipOptions {
            get {
                return ResourceManager.GetString("DockPaneCaption_ToolTipOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Content: The content must be auto-hide state and associates with this DockPanel. ähnelt.
        /// </summary>
        internal static string DockPanel_ActiveAutoHideContent_InvalidValue {
            get {
                return ResourceManager.GetString("DockPanel_ActiveAutoHideContent_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occurs when the value of the AutoHideWindow&apos;s ActiveContent changed. ähnelt.
        /// </summary>
        internal static string DockPanel_ActiveAutoHideContentChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActiveAutoHideContentChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occurs when the value of ActiveContentProperty changed. ähnelt.
        /// </summary>
        internal static string DockPanel_ActiveContentChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActiveContentChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occurs when the value of ActiveDocument property changed. ähnelt.
        /// </summary>
        internal static string DockPanel_ActiveDocumentChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActiveDocumentChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occurs when the value of ActivePane property changed. ähnelt.
        /// </summary>
        internal static string DockPanel_ActivePaneChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActivePaneChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Determines if the drag and drop docking is allowed. ähnelt.
        /// </summary>
        internal static string DockPanel_AllowEndUserDocking_Description {
            get {
                return ResourceManager.GetString("DockPanel_AllowEndUserDocking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Determines if the drag and drop nested docking is allowed. ähnelt.
        /// </summary>
        internal static string DockPanel_AllowEndUserNestedDocking_Description {
            get {
                return ResourceManager.GetString("DockPanel_AllowEndUserNestedDocking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occurs when a content added to the DockPanel. ähnelt.
        /// </summary>
        internal static string DockPanel_ContentAdded_Description {
            get {
                return ResourceManager.GetString("DockPanel_ContentAdded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occurs when a content removed from the DockPanel. ähnelt.
        /// </summary>
        internal static string DockPanel_ContentRemoved_Description {
            get {
                return ResourceManager.GetString("DockPanel_ContentRemoved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The default size of float window. ähnelt.
        /// </summary>
        internal static string DockPanel_DefaultFloatWindowSize_Description {
            get {
                return ResourceManager.GetString("DockPanel_DefaultFloatWindowSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provides Visual Studio .Net style docking. ähnelt.
        /// </summary>
        internal static string DockPanel_Description {
            get {
                return ResourceManager.GetString("DockPanel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size of the bottom docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels. ähnelt.
        /// </summary>
        internal static string DockPanel_DockBottomPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockBottomPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size of the left docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels. ähnelt.
        /// </summary>
        internal static string DockPanel_DockLeftPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockLeftPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The visual skin to use when displaying the docked windows. ähnelt.
        /// </summary>
        internal static string DockPanel_DockPanelSkin {
            get {
                return ResourceManager.GetString("DockPanel_DockPanelSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size of the right docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels. ähnelt.
        /// </summary>
        internal static string DockPanel_DockRightPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockRightPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size of the top docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels. ähnelt.
        /// </summary>
        internal static string DockPanel_DockTopPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockTopPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The style of the document window. ähnelt.
        /// </summary>
        internal static string DockPanel_DocumentStyle_Description {
            get {
                return ResourceManager.GetString("DockPanel_DocumentStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Determines where the tab strip for Document style content is drawn. ähnelt.
        /// </summary>
        internal static string DockPanel_DocumentTabStripLocation {
            get {
                return ResourceManager.GetString("DockPanel_DocumentTabStripLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The DockPanel has already been initialized. ähnelt.
        /// </summary>
        internal static string DockPanel_LoadFromXml_AlreadyInitialized {
            get {
                return ResourceManager.GetString("DockPanel_LoadFromXml_AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The configuration file&apos;s version is invalid. ähnelt.
        /// </summary>
        internal static string DockPanel_LoadFromXml_InvalidFormatVersion {
            get {
                return ResourceManager.GetString("DockPanel_LoadFromXml_InvalidFormatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The XML file format is invalid. ähnelt.
        /// </summary>
        internal static string DockPanel_LoadFromXml_InvalidXmlFormat {
            get {
                return ResourceManager.GetString("DockPanel_LoadFromXml_InvalidXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid parent form. When using DockingMdi or SystemMdi document style, the DockPanel control must be the child control of the main MDI container form. ähnelt.
        /// </summary>
        internal static string DockPanel_ParentForm_Invalid {
            get {
                return ResourceManager.GetString("DockPanel_ParentForm_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DockPanel configuration file. Author: Weifen Luo, all rights reserved. ähnelt.
        /// </summary>
        internal static string DockPanel_Persistor_XmlFileComment1 {
            get {
                return ResourceManager.GetString("DockPanel_Persistor_XmlFileComment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die !!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!! ähnelt.
        /// </summary>
        internal static string DockPanel_Persistor_XmlFileComment2 {
            get {
                return ResourceManager.GetString("DockPanel_Persistor_XmlFileComment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Indicates whether the control layout is right-to-left when the RightToLeft property is set to Yes. ähnelt.
        /// </summary>
        internal static string DockPanel_RightToLeftLayout_Description {
            get {
                return ResourceManager.GetString("DockPanel_RightToLeftLayout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Index: The index is out of range. ähnelt.
        /// </summary>
        internal static string DockPanel_SetPaneIndex_InvalidIndex {
            get {
                return ResourceManager.GetString("DockPanel_SetPaneIndex_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Pane: DockPane not within the collection. ähnelt.
        /// </summary>
        internal static string DockPanel_SetPaneIndex_InvalidPane {
            get {
                return ResourceManager.GetString("DockPanel_SetPaneIndex_InvalidPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shows the hidden autohide content when hovering over the tab.  When disabled, the tab must be clicked to show the content. ähnelt.
        /// </summary>
        internal static string DockPanel_ShowAutoHideContentOnHover_Description {
            get {
                return ResourceManager.GetString("DockPanel_ShowAutoHideContentOnHover_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show close button on each tab ähnelt.
        /// </summary>
        internal static string DockPanel_ShowCloseButtonOnEachTab_Description {
            get {
                return ResourceManager.GetString("DockPanel_ShowCloseButtonOnEachTab_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Determines if the document icon will be displayed in the tab strip. ähnelt.
        /// </summary>
        internal static string DockPanel_ShowDocumentIcon_Description {
            get {
                return ResourceManager.GetString("DockPanel_ShowDocumentIcon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support deeply nested controls.  Disabling this setting may improve resize performance but may cause heavily nested content not to resize. ähnelt.
        /// </summary>
        internal static string DockPanel_SupportDeeplyNestedContent_Description {
            get {
                return ResourceManager.GetString("DockPanel_SupportDeeplyNestedContent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string DockPaneStrip_ToolTipClose {
            get {
                return ResourceManager.GetString("DockPaneStrip_ToolTipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Window List ähnelt.
        /// </summary>
        internal static string DockPaneStrip_ToolTipWindowList {
            get {
                return ResourceManager.GetString("DockPaneStrip_ToolTipWindowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid argument: DockPanel can not be &quot;null&quot;. ähnelt.
        /// </summary>
        internal static string FloatWindow_Constructor_NullDockPanel {
            get {
                return ResourceManager.GetString("FloatWindow_Constructor_NullDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Index: The index is out of range. ähnelt.
        /// </summary>
        internal static string FloatWindow_SetPaneIndex_InvalidIndex {
            get {
                return ResourceManager.GetString("FloatWindow_SetPaneIndex_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Pane: DockPane not within the collection. ähnelt.
        /// </summary>
        internal static string FloatWindow_SetPaneIndex_InvalidPane {
            get {
                return ResourceManager.GetString("FloatWindow_SetPaneIndex_InvalidPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid DockPanel. ähnelt.
        /// </summary>
        internal static string IDockDragSource_DockTo_InvalidPanel {
            get {
                return ResourceManager.GetString("IDockDragSource_DockTo_InvalidPanel", resourceCulture);
            }
        }
    }
}
