//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsCoreDockPanelSuite.Docking {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsCoreDockPanelSuite.Docking.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Docking 的本地化字符串。
        /// </summary>
        internal static string Category_Docking {
            get {
                return ResourceManager.GetString("Category_Docking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Docking Notification 的本地化字符串。
        /// </summary>
        internal static string Category_DockingNotification {
            get {
                return ResourceManager.GetString("Category_DockingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance 的本地化字符串。
        /// </summary>
        internal static string Category_Performance {
            get {
                return ResourceManager.GetString("Category_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property Changed 的本地化字符串。
        /// </summary>
        internal static string Category_PropertyChanged {
            get {
                return ResourceManager.GetString("Category_PropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Float) 的本地化字符串。
        /// </summary>
        internal static string DockAreaEditor_FloatCheckBoxText {
            get {
                return ResourceManager.GetString("DockAreaEditor_FloatCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines if end user drag and drop docking is allowed. 的本地化字符串。
        /// </summary>
        internal static string DockContent_AllowEndUserDocking_Description {
            get {
                return ResourceManager.GetString("DockContent_AllowEndUserDocking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The size to display the content in auto hide mode. Value &lt; 1 to specify the size in portion; value &gt;= 1 to specify the size in pixel. 的本地化字符串。
        /// </summary>
        internal static string DockContent_AutoHidePortion_Description {
            get {
                return ResourceManager.GetString("DockContent_AutoHidePortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable/Disable the close button of the content. 的本地化字符串。
        /// </summary>
        internal static string DockContent_CloseButton_Description {
            get {
                return ResourceManager.GetString("DockContent_CloseButton_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shows or hides the close button of the content. This property does not function with System MDI Document Style. 的本地化字符串。
        /// </summary>
        internal static string DockContent_CloseButtonVisible_Description {
            get {
                return ResourceManager.GetString("DockContent_CloseButtonVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The form must be of type IDockContent. 的本地化字符串。
        /// </summary>
        internal static string DockContent_Constructor_InvalidForm {
            get {
                return ResourceManager.GetString("DockContent_Constructor_InvalidForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gets or sets a value indicating in which area of the DockPanel the content allowed to show. 的本地化字符串。
        /// </summary>
        internal static string DockContent_DockAreas_Description {
            get {
                return ResourceManager.GetString("DockContent_DockAreas_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the value of DockState property changed. 的本地化字符串。
        /// </summary>
        internal static string DockContent_DockStateChanged_Description {
            get {
                return ResourceManager.GetString("DockContent_DockStateChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates the content will be hidden instead of being closed. 的本地化字符串。
        /// </summary>
        internal static string DockContent_HideOnClose_Description {
            get {
                return ResourceManager.GetString("DockContent_HideOnClose_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The desired docking state when first showing. 的本地化字符串。
        /// </summary>
        internal static string DockContent_ShowHint_Description {
            get {
                return ResourceManager.GetString("DockContent_ShowHint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Context menu displayed for the dock pane tab strip. 的本地化字符串。
        /// </summary>
        internal static string DockContent_TabPageContextMenu_Description {
            get {
                return ResourceManager.GetString("DockContent_TabPageContextMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The tab text displayed in the dock pane. If not set, the Text property will be used. 的本地化字符串。
        /// </summary>
        internal static string DockContent_TabText_Description {
            get {
                return ResourceManager.GetString("DockContent_TabText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The text displayed when mouse hovers over the tab. 的本地化字符串。
        /// </summary>
        internal static string DockContent_ToolTipText_Description {
            get {
                return ResourceManager.GetString("DockContent_ToolTipText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided value is out of range. 的本地化字符串。
        /// </summary>
        internal static string DockContentHandler_AutoHidePortion_OutOfRange {
            get {
                return ResourceManager.GetString("DockContentHandler_AutoHidePortion_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Value: The value of DockAreas conflicts with current DockState. 的本地化字符串。
        /// </summary>
        internal static string DockContentHandler_DockAreas_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_DockAreas_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The pane is invalid. Check the IsFloat and DockPanel properties of this dock pane. 的本地化字符串。
        /// </summary>
        internal static string DockContentHandler_DockPane_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_DockPane_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The pane is invalid. Check the IsFloat and DockPanel properties of this dock pane. 的本地化字符串。
        /// </summary>
        internal static string DockContentHandler_FloatPane_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_FloatPane_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid value, conflicts with DockableAreas  property. 的本地化字符串。
        /// </summary>
        internal static string DockContentHandler_IsFloat_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_IsFloat_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The dock state is invalid. 的本地化字符串。
        /// </summary>
        internal static string DockContentHandler_SetDockState_InvalidState {
            get {
                return ResourceManager.GetString("DockContentHandler_SetDockState_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The dock panel is null. 的本地化字符串。
        /// </summary>
        internal static string DockContentHandler_SetDockState_NullPanel {
            get {
                return ResourceManager.GetString("DockContentHandler_SetDockState_NullPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid beforeContent, it must be contained by the pane. 的本地化字符串。
        /// </summary>
        internal static string DockContentHandler_Show_InvalidBeforeContent {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_InvalidBeforeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid DockState: Content can not be showed as &quot;Unknown&quot; or &quot;Hidden&quot;. 的本地化字符串。
        /// </summary>
        internal static string DockContentHandler_Show_InvalidDockState {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_InvalidDockState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The previous pane is invalid. It can not be null, and its docking state must not be auto-hide. 的本地化字符串。
        /// </summary>
        internal static string DockContentHandler_Show_InvalidPrevPane {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_InvalidPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DockPanel can not be null. 的本地化字符串。
        /// </summary>
        internal static string DockContentHandler_Show_NullDockPanel {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_NullDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Pane can not be null. 的本地化字符串。
        /// </summary>
        internal static string DockContentHandler_Show_NullPane {
            get {
                return ResourceManager.GetString("DockContentHandler_Show_NullPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid value, check DockableAreas property. 的本地化字符串。
        /// </summary>
        internal static string DockContentHandler_ShowHint_InvalidValue {
            get {
                return ResourceManager.GetString("DockContentHandler_ShowHint_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Context menu displayed for the dock pane tab strip. 的本地化字符串。
        /// </summary>
        internal static string DockHandler_TabPageContextMenuStrip_Description {
            get {
                return ResourceManager.GetString("DockHandler_TabPageContextMenuStrip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Content: ActiveContent must be one of the visible contents, or null if there is no visible content. 的本地化字符串。
        /// </summary>
        internal static string DockPane_ActiveContent_InvalidValue {
            get {
                return ResourceManager.GetString("DockPane_ActiveContent_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid argument: Content can not be &quot;null&quot;. 的本地化字符串。
        /// </summary>
        internal static string DockPane_Constructor_NullContent {
            get {
                return ResourceManager.GetString("DockPane_Constructor_NullContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid argument: The content&apos;s DockPanel can not be &quot;null&quot;. 的本地化字符串。
        /// </summary>
        internal static string DockPane_Constructor_NullDockPanel {
            get {
                return ResourceManager.GetString("DockPane_Constructor_NullDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified container conflicts with the IsFloat property. 的本地化字符串。
        /// </summary>
        internal static string DockPane_DockTo_InvalidContainer {
            get {
                return ResourceManager.GetString("DockPane_DockTo_InvalidContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The previous pane does not exist in the nested docking pane collection. 的本地化字符串。
        /// </summary>
        internal static string DockPane_DockTo_NoPrevPane {
            get {
                return ResourceManager.GetString("DockPane_DockTo_NoPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The container can not be null. 的本地化字符串。
        /// </summary>
        internal static string DockPane_DockTo_NullContainer {
            get {
                return ResourceManager.GetString("DockPane_DockTo_NullContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The previous pane can not be null when the nested docking pane collection is not empty. 的本地化字符串。
        /// </summary>
        internal static string DockPane_DockTo_NullPrevPane {
            get {
                return ResourceManager.GetString("DockPane_DockTo_NullPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The previous pane can not be itself. 的本地化字符串。
        /// </summary>
        internal static string DockPane_DockTo_SelfPrevPane {
            get {
                return ResourceManager.GetString("DockPane_DockTo_SelfPrevPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Content: Content not within the collection. 的本地化字符串。
        /// </summary>
        internal static string DockPane_SetContentIndex_InvalidContent {
            get {
                return ResourceManager.GetString("DockPane_SetContentIndex_InvalidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Index: The index is out of range. 的本地化字符串。
        /// </summary>
        internal static string DockPane_SetContentIndex_InvalidIndex {
            get {
                return ResourceManager.GetString("DockPane_SetContentIndex_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The state for the dock pane is invalid. 的本地化字符串。
        /// </summary>
        internal static string DockPane_SetDockState_InvalidState {
            get {
                return ResourceManager.GetString("DockPane_SetDockState_InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Content: The content must be auto-hide state and associates with this DockPanel. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_ActiveAutoHideContent_InvalidValue {
            get {
                return ResourceManager.GetString("DockPanel_ActiveAutoHideContent_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the value of the AutoHideWindow&apos;s ActiveContent changed. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_ActiveAutoHideContentChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActiveAutoHideContentChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the value of ActiveContentProperty changed. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_ActiveContentChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActiveContentChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the value of ActiveDocument property changed. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_ActiveDocumentChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActiveDocumentChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when the value of ActivePane property changed. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_ActivePaneChanged_Description {
            get {
                return ResourceManager.GetString("DockPanel_ActivePaneChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines if the drag and drop docking is allowed. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_AllowEndUserDocking_Description {
            get {
                return ResourceManager.GetString("DockPanel_AllowEndUserDocking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines if the drag and drop nested docking is allowed. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_AllowEndUserNestedDocking_Description {
            get {
                return ResourceManager.GetString("DockPanel_AllowEndUserNestedDocking_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when a content added to the DockPanel. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_ContentAdded_Description {
            get {
                return ResourceManager.GetString("DockPanel_ContentAdded_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when a content removed from the DockPanel. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_ContentRemoved_Description {
            get {
                return ResourceManager.GetString("DockPanel_ContentRemoved_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default size of float window. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_DefaultFloatWindowSize_Description {
            get {
                return ResourceManager.GetString("DockPanel_DefaultFloatWindowSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provides Visual Studio .Net style docking. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_Description {
            get {
                return ResourceManager.GetString("DockPanel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size of the bottom docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_DockBottomPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockBottomPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size of the left docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_DockLeftPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockLeftPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The visual skin to use when displaying the docked windows. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_DockPanelSkin_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockPanelSkin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size of the right docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_DockRightPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockRightPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size of the top docking window. Value &lt; 1 to specify the size in portion; value &gt; 1 to specify the size in pixels. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_DockTopPortion_Description {
            get {
                return ResourceManager.GetString("DockPanel_DockTopPortion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Occurs when a document or pane is dragged within the dock panel. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_DocumentDragged_Description {
            get {
                return ResourceManager.GetString("DockPanel_DocumentDragged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The style of the document window. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_DocumentStyle_Description {
            get {
                return ResourceManager.GetString("DockPanel_DocumentStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines where the tab strip for Document style content is drawn. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_DocumentTabStripLocation_Description {
            get {
                return ResourceManager.GetString("DockPanel_DocumentTabStripLocation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DockPanel has already been initialized. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_LoadFromXml_AlreadyInitialized {
            get {
                return ResourceManager.GetString("DockPanel_LoadFromXml_AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The configuration file&apos;s version is invalid. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_LoadFromXml_InvalidFormatVersion {
            get {
                return ResourceManager.GetString("DockPanel_LoadFromXml_InvalidFormatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The XML file format is invalid. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_LoadFromXml_InvalidXmlFormat {
            get {
                return ResourceManager.GetString("DockPanel_LoadFromXml_InvalidXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid parent form. When using DockingMdi or SystemMdi document style, the DockPanel control must be the child control of the main MDI container form. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_ParentForm_Invalid {
            get {
                return ResourceManager.GetString("DockPanel_ParentForm_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DockPanel configuration file. Author: Weifen Luo, all rights reserved. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_Persistor_XmlFileComment1 {
            get {
                return ResourceManager.GetString("DockPanel_Persistor_XmlFileComment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 !!! AUTOMATICALLY GENERATED FILE. DO NOT MODIFY !!! 的本地化字符串。
        /// </summary>
        internal static string DockPanel_Persistor_XmlFileComment2 {
            get {
                return ResourceManager.GetString("DockPanel_Persistor_XmlFileComment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indicates whether the control layout is right-to-left when the RightToLeft property is set to Yes. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_RightToLeftLayout_Description {
            get {
                return ResourceManager.GetString("DockPanel_RightToLeftLayout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Index: The index is out of range. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_SetPaneIndex_InvalidIndex {
            get {
                return ResourceManager.GetString("DockPanel_SetPaneIndex_InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Pane: DockPane not within the collection. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_SetPaneIndex_InvalidPane {
            get {
                return ResourceManager.GetString("DockPanel_SetPaneIndex_InvalidPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shows the hidden autohide content when hovering over the tab.  When disabled, the tab must be clicked to show the content. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_ShowAutoHideContentOnHover_Description {
            get {
                return ResourceManager.GetString("DockPanel_ShowAutoHideContentOnHover_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Determines if the document icon will be displayed in the tab strip. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_ShowDocumentIcon_Description {
            get {
                return ResourceManager.GetString("DockPanel_ShowDocumentIcon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support deeply nested controls.  Disabling this setting may improve resize performance but may cause heavily nested content not to resize. 的本地化字符串。
        /// </summary>
        internal static string DockPanel_SupportDeeplyNestedContent_Description {
            get {
                return ResourceManager.GetString("DockPanel_SupportDeeplyNestedContent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid argument: DockPanel can not be &quot;null&quot;. 的本地化字符串。
        /// </summary>
        internal static string FloatWindow_Constructor_NullDockPanel {
            get {
                return ResourceManager.GetString("FloatWindow_Constructor_NullDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid DockPanel. 的本地化字符串。
        /// </summary>
        internal static string IDockDragSource_DockTo_InvalidPanel {
            get {
                return ResourceManager.GetString("IDockDragSource_DockTo_InvalidPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before applying themes all dock contents must be closed. 的本地化字符串。
        /// </summary>
        internal static string Theme_DockContentNotClosed {
            get {
                return ResourceManager.GetString("Theme_DockContentNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before applying themes all float windows must be closed. 的本地化字符串。
        /// </summary>
        internal static string Theme_FloatWindowNotClosed {
            get {
                return ResourceManager.GetString("Theme_FloatWindowNotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before applying themes all factories must be configured. 的本地化字符串。
        /// </summary>
        internal static string Theme_MissingFactory {
            get {
                return ResourceManager.GetString("Theme_MissingFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DockPanel.Theme must be set to a valid theme. 的本地化字符串。
        /// </summary>
        internal static string Theme_NoTheme {
            get {
                return ResourceManager.GetString("Theme_NoTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before applying themes all panes must be closed. 的本地化字符串。
        /// </summary>
        internal static string Theme_PaneNotClosed {
            get {
                return ResourceManager.GetString("Theme_PaneNotClosed", resourceCulture);
            }
        }
    }
}
